### ISSUE TITLE
[Project] Project Questions

### ISSUE THREAD

**Issue by Stetsed** [sreedevk/pocketbase-sdk-rust#17]
Good evening,

I have a few questions about this project. First of all is it still being updated, I see an old PR but want to know if it's still being maintained. Secondly I would go through your example code again as in it's current state it will not function due to the variables being wrongly named, if you do not have the time I could submit a PR for this.

Thirdly is it possible to delete with a filter, I want to for example delete all entries where one of the values is equal to something(for example a name).

**Comment by sreedevk** [comment]
Hey @Stetsed,

1. I was unhappy with a few decisions I made while creating the PR that's open. So I am looking into salvaging the good parts from it. I am planning to do the next release by the end of this month. 
2. Any contributions are welcome, please feel free to raise a PR against the main branch. It'll definitely help in making things faster.
3. In it's current state, you can only use the delete API with a single record ID. I will incorporate bulk operations with filters after the next release (where i will first solve some problems with the fundamental architecture)

**Comment by Stetsed** [comment]
Thanks for the comments, I will send a PR when I got the time for it so should be soon, but still thanks for the API as it's really useful and if you are able to implement that bulk operations then that would be perfect as right now for bulk operations I gotta stick to MySQL. But still without your library I wouldn't be able to move atleast the bulk of my stuff to pocket base

**Comment by sreedevk** [comment]
@Stetsed No problem. Thank you for your inputs.

**Comment by Stetsed** [comment]
@sreedevk I was looking at maybe helping you implement some of the suggestions I laid out, and wanted to ask if you had any plans for how you would implement mass deletion? Because from what I can see this isn't possible with the Pocketbase API at this moment in times? Wanted to know if you had a plan on how you where going to do this which I could maybe start working on, because right now I do not see a way to implement it

**Comment by sreedevk** [comment]
Hello @Stetsed, I appreciate your contributions, support and interest in the library. Currently, I am working on a local branch that is an overhaul of the current architecture. I will push the updated branch as soon as I can get it to a working condition. Once this is done, we can implement new features as needed. There are a few things that are really bad with the current setup. The changes I'm working on will create a stable base for us to build new features. I'll post updates on this thread to keep you in the loop.

**Comment by Stetsed** [comment]
Sounds good @sreedevk , I'll wait till that branch comes out then and see if I could be of help then.

**Comment by sreedevk** [comment]
@Stetsed I have made the changes I was talking about in - https://github.com/sreedevk/pocketbase-sdk-rust/pull/19/files feel free to check it out. I will write more tests & publish it as V0.1.1 soon. Contributions are welcome.
