### ISSUE TITLE
Use `Box<dyn Error + Send + Sync>` instead of `Box<dyn Error>` as error type

### ISSUE THREAD

**Issue by kangalio** [sreedevk/pocketbase-sdk-rust#20]
That makes the error type more usable in async context. A non-Send/Sync type cannot be held across an await point in most cases, which makes dealing with pocketbase-sdk-rust's error types a bit painful in async.

(I'm not a user of pocketbase-sdk-rust, but have seen a user in serenity's support channel struggle with this)

![image](https://user-images.githubusercontent.com/21220820/233336608-0586ee52-1d97-47c2-87ea-cb472b9fbabd.png)

**Comment by sreedevk** [comment]
Thank you @kangalio for the input. I am currently rewriting the application using ureq. The requests are blocking. I am leaving it to the user of the SDK to handle concurrency. https://github.com/sreedevk/pocketbase-sdk-rust/pull/19
